apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: saiaryansoma/e-commerce-backend:latest # Jenkins will update this
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mysql-service" # Correctly points to the MySQL service
        # --- ADD THIS SECTION TO SECURELY PROVIDE THE DB PASSWORD ---
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass      # Name of the Secret we created
              key: password        # Key inside the Secret
        # ----------------------------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000